name: Tag on Merge to Master
on:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to fetch all commits

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag on Merge
        id: tag
        run: |
          # Calculate the new version and tag
          new_tag=$(your-tagging-script.sh) # Replace with your tagging logic
          git tag -a $new_tag -m "Tagging version $new_tag"
          git push origin $new_tag
          echo "::set-output name=new_tag::$new_tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        run: echo "new_tag=${{ steps.tag.outputs.new_tag }}" >> $GITHUB_ENV
