name: Version Tagging

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - synchronize
    branches:
      - master

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Set Up Git
        run: git config --global --add safe.directory /github/workspace

      - name: Bump Version and Push Tag
        id: bump
        uses: anothrNick/github-tag-action@1.64.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          PRERELEASE: true
          PRERELEASE_SUFFIX: -pr

      - name: Overwrite Pre-release Tag
        if: github.event_name == 'pull_request'
        run: git tag -f ${{ steps.bump.outputs.new_tag }}

      - name: Push Tag
        if: github.event_name == 'pull_request'
        run: git push origin ${{ steps.bump.outputs.new_tag }}
