name: Pre-release Tag on Pull Request
on:
  pull_request:
    types:
      - synchronize
    branches:
      - '*'

jobs:
  pre_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 # Required to fetch all commits

      - name: Set up Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Pre-release Tag
        id: pre_release_tag
        run: |
          # Calculate the new pre-release version and tag
          new_pre_release_tag=$(your-pre-release-tagging-script.sh) # Replace with your pre-release tagging logic
          git tag -a $new_pre_release_tag -m "Pre-release version $new_pre_release_tag"
          git push origin $new_pre_release_tag
          echo "::set-output name=new_pre_release_tag::$new_pre_release_tag"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set outputs
        run: echo "new_pre_release_tag=${{ steps.pre_release_tag.outputs.new_pre_release_tag }}" >> $GITHUB_ENV
