name: Prepare release

on:
  push:
    tags:
      - '*'
      #- "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - uses: ncipollo/release-action@v1
        with:
          #artifacts: "release.tar.gz,foo/*.txt"
          #bodyFile: "body.md"
          token: ${{ secrets.GITHUB_TOKEN }}


#      - name: Release
#        uses: docker://antonyurchenko/git-release:v5
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: build/*.zip