name: Maven CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        cache: maven
    
    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix:  ${{ github.event.pull_request.head.sha }}
#        append_to_pre_release_tag: PR_TAG_ alpha.${GITHUB_SHA::6}
        # ${GITHUB_REF#refs/heads/}_$(git rev-parse --short "$GITHUB_SHA")

        #sds

