name: Maven CI/CD

on:
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
        cache: maven
    
    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: View context attributes
      uses: actions/github-script@v6
      with:
        script: console.log(context)

    - uses: actions/github-script@v6
      env:
        FIRST_NAME: Mona
        LAST_NAME: Octocat
      with:
        script: |
          const { FIRST_NAME, LAST_NAME } = process.env    
          console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`)

    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/<tagname>',
            sha: context.sha
          })

