name: Tag PR
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        uses: gabriel-amyot/github-tag-action@0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          PRERELEASE: true
          PRERELEASE_SUFFIX: dev
          DEFAULT_BUMP: patch